version: 1

formatters:
  simple:
    format: "%(asctime)s %(module)s line:%(lineno)d %(name)s %(levelname)s: %(message)s "

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: test.log
    formatter: simple
    mode: w

loggers:
  dev:
    handlers: [console, file_handler]
    level: DEBUG
    propagate: no

  test:
    handlers: [console, file_handler]
    level: INFO
    propagate: no

root:
  handlers: [console, file_handler]
  level: DEBUG